# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN if [ $(command -v apt-get) ]; then \
    apt-get update \
    && \
    apt-get install -y --no-install-recommends \
    python3 \
    sudo \
    bash \
    ca-certificates \
    iproute2 \
    init \
    && \
    apt-get clean; \
    fi
