---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: itnok-ubuntu-bionic
    image: ${MOLECULE_DISTRO:-'ubuntu:bionic'}
    pre_build_image: False
  - name: itnok-ubuntu-focal
    image: ${MOLECULE_DISTRO:-'ubuntu:focal'}
    pre_build_image: False
  - name: itnok-debian-buster
    image: ${MOLECULE_DISTRO:-'debian:buster'}
    pre_build_image: False
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: "/usr/bin/python3"
verifier:
  name: ansible
