---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Include Role main task
    include_role:
      name: itnok.is_ubuntu

  - name: Verify is_ubuntu_localhost is False in Molecule container
    assert:
      that: not is_ubuntu_localhost

  - name: Verify is_ubuntu_inside_container is True in Molecule container
    assert:
      that: is_ubuntu_inside_container

  - name: Verify is_ubuntu_behind_proxy is False in Molecule container
    assert:
      that: not is_ubuntu_behind_proxy

  - name: Verify is_ubuntu_network_reachable is True in Molecule container
    assert:
      that: is_ubuntu_network_reachable

  - name: Verify is_ubuntu_url_unreachable_list is empty in Molecule container
    assert:
      that: (is_ubuntu_url_unreachable_list | length) == 0

  - name: Include again Role main task to verify URLs are checked again using new data
    include_role:
      name: itnok.is_ubuntu
    vars:
      is_test_url_list:
        - "https://github.com/"
        - "https://gitlab.com/"
        - "http://this-domain-does-not-exist-and-should-not-return-a-200.com/"

  - name: Verify is_ubuntu_localhost is still False in Molecule container
    assert:
      that: not is_ubuntu_localhost

  - name: Verify is_ubuntu_inside_container is still True in Molecule container
    assert:
      that: is_ubuntu_inside_container

  - name: Verify is_ubuntu_behind_proxy is still False in Molecule container
    assert:
      that: not is_ubuntu_behind_proxy

  - name: Verify is_ubuntu_network_reachable is now False in Molecule container
    assert:
      that: not is_ubuntu_network_reachable

  - name: Verify is_ubuntu_url_unreachable_list has 1 element in Molecule container
    assert:
      that: (is_ubuntu_url_unreachable_list | length) == 1
